version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:05"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    assignees:
      - ssbingo
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:05"
      timezone: Europe/Berlin
    open-pull-requests-limit: 15
    assignees:
      - ssbingo
 