'use strict';

/**
 * Sigenergy Modbus V2.5 Register Definitions
 * Based on official Sigenergy Modbus Protocol V2.5 (2025-02-19)
 */

// ============================================================
// Section 5.1 - Plant Running Information (Read-Only, slave 247)
// ============================================================
const PLANT_READ_REGISTERS = [
	{
		addr: 30000,
		qty: 2,
		name: 'plant.systemTime',
		type: 'U32',
		gain: 1,
		unit: 's',
		role: 'value.time',
		desc: 'System time (Epoch seconds)',
	},
	{
		addr: 30002,
		qty: 1,
		name: 'plant.systemTimeZone',
		type: 'S16',
		gain: 1,
		unit: 'min',
		role: 'value',
		desc: 'System time zone offset (minutes)',
	},
	{
		addr: 30003,
		qty: 1,
		name: 'plant.emsWorkMode',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'EMS work mode: 0=MaxSelfConsumption,1=AI,2=TOU,7=RemoteEMS',
	},
	{
		addr: 30004,
		qty: 1,
		name: 'plant.gridSensorStatus',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'indicator',
		desc: 'Grid sensor status: 0=disconnected, 1=connected',
	},
	{
		addr: 30005,
		qty: 2,
		name: 'plant.gridActivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Grid active power (>0 buy, <0 sell)',
	},
	{
		addr: 30007,
		qty: 2,
		name: 'plant.gridReactivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Grid reactive power',
	},
	{
		addr: 30009,
		qty: 1,
		name: 'plant.onOffGridStatus',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'On/Off grid: 0=on,1=off(auto),2=off(manual)',
	},
	{
		addr: 30010,
		qty: 2,
		name: 'plant.maxActivePower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Max active power (base value)',
	},
	{
		addr: 30012,
		qty: 2,
		name: 'plant.maxApparentPower',
		type: 'U32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Max apparent power (base value)',
	},
	{
		addr: 30014,
		qty: 1,
		name: 'plant.essSoc',
		type: 'U16',
		gain: 10,
		unit: '%',
		role: 'value.battery',
		desc: 'ESS State of Charge',
	},
	{
		addr: 30015,
		qty: 2,
		name: 'plant.phaseAActivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Plant phase A active power',
	},
	{
		addr: 30017,
		qty: 2,
		name: 'plant.phaseBActivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Plant phase B active power',
	},
	{
		addr: 30019,
		qty: 2,
		name: 'plant.phaseCActivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Plant phase C active power',
	},
	{
		addr: 30021,
		qty: 2,
		name: 'plant.phaseAReactivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Plant phase A reactive power',
	},
	{
		addr: 30023,
		qty: 2,
		name: 'plant.phaseBReactivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Plant phase B reactive power',
	},
	{
		addr: 30025,
		qty: 2,
		name: 'plant.phaseCReactivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Plant phase C reactive power',
	},
	{
		addr: 30027,
		qty: 1,
		name: 'plant.generalAlarm1',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'General Alarm 1 (PCS alarms, see Appendix 2)',
	},
	{
		addr: 30028,
		qty: 1,
		name: 'plant.generalAlarm2',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'General Alarm 2 (PCS alarms, see Appendix 3)',
	},
	{
		addr: 30029,
		qty: 1,
		name: 'plant.generalAlarm3',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'General Alarm 3 (ESS alarms, see Appendix 4)',
	},
	{
		addr: 30030,
		qty: 1,
		name: 'plant.generalAlarm4',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'General Alarm 4 (Gateway alarms, see Appendix 5)',
	},
	{
		addr: 30031,
		qty: 2,
		name: 'plant.activePower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Plant active power',
	},
	{
		addr: 30033,
		qty: 2,
		name: 'plant.reactivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Plant reactive power',
	},
	{
		addr: 30035,
		qty: 2,
		name: 'plant.pvPower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Photovoltaic power',
	},
	{
		addr: 30037,
		qty: 2,
		name: 'plant.essPower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'ESS power (<0=discharging, >0=charging)',
	},
	{
		addr: 30039,
		qty: 2,
		name: 'plant.availableMaxActivePower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Available max active power',
	},
	{
		addr: 30041,
		qty: 2,
		name: 'plant.availableMinActivePower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Available min active power (absorption)',
	},
	{
		addr: 30043,
		qty: 2,
		name: 'plant.availableMaxReactivePower',
		type: 'U32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Available max reactive power',
	},
	{
		addr: 30045,
		qty: 2,
		name: 'plant.availableMinReactivePower',
		type: 'U32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Available min reactive power',
	},
	{
		addr: 30047,
		qty: 2,
		name: 'plant.essAvailableMaxChargingPower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'ESS available max charging power',
	},
	{
		addr: 30049,
		qty: 2,
		name: 'plant.essAvailableMaxDischargingPower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'ESS available max discharging power',
	},
	{
		addr: 30051,
		qty: 1,
		name: 'plant.runningState',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'Plant running state (0=Standby,1=Running,2=Fault,3=Shutdown)',
	},
	{
		addr: 30052,
		qty: 2,
		name: 'plant.gridPhaseAActivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Grid sensor Phase A active power',
	},
	{
		addr: 30054,
		qty: 2,
		name: 'plant.gridPhaseBActivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Grid sensor Phase B active power',
	},
	{
		addr: 30056,
		qty: 2,
		name: 'plant.gridPhaseCActivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Grid sensor Phase C active power',
	},
	{
		addr: 30058,
		qty: 2,
		name: 'plant.gridPhaseAReactivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Grid sensor Phase A reactive power',
	},
	{
		addr: 30060,
		qty: 2,
		name: 'plant.gridPhaseBReactivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Grid sensor Phase B reactive power',
	},
	{
		addr: 30062,
		qty: 2,
		name: 'plant.gridPhaseCReactivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Grid sensor Phase C reactive power',
	},
	{
		addr: 30064,
		qty: 2,
		name: 'plant.essAvailableMaxChargingCapacity',
		type: 'U32',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'ESS available max charging capacity',
	},
	{
		addr: 30066,
		qty: 2,
		name: 'plant.essAvailableMaxDischargingCapacity',
		type: 'U32',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'ESS available max discharging capacity',
	},
	{
		addr: 30068,
		qty: 2,
		name: 'plant.essRatedChargingPower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'ESS rated charging power',
	},
	{
		addr: 30070,
		qty: 2,
		name: 'plant.essRatedDischargingPower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'ESS rated discharging power',
	},
	{
		addr: 30072,
		qty: 1,
		name: 'plant.generalAlarm5',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'General Alarm 5 (DC Charger alarms, see Appendix 11)',
	},
	{
		addr: 30083,
		qty: 2,
		name: 'plant.essRatedEnergyCapacity',
		type: 'U32',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'ESS rated energy capacity',
	},
	{
		addr: 30085,
		qty: 1,
		name: 'plant.essChargeSOC',
		type: 'U16',
		gain: 10,
		unit: '%',
		role: 'value.battery',
		desc: 'ESS charge cut-off SOC',
	},
	{
		addr: 30086,
		qty: 1,
		name: 'plant.essDischargeSOC',
		type: 'U16',
		gain: 10,
		unit: '%',
		role: 'value.battery',
		desc: 'ESS discharge cut-off SOC',
	},
	{
		addr: 30087,
		qty: 1,
		name: 'plant.essSoh',
		type: 'U16',
		gain: 10,
		unit: '%',
		role: 'value.battery',
		desc: 'ESS State of Health (weighted average)',
	},
];

// ============================================================
// Section 5.2 - Plant Parameter Setting (Holding, slave 0 or 247)
// ============================================================
const PLANT_WRITE_REGISTERS = [
	{
		addr: 40000,
		qty: 1,
		name: 'plant.control.startStop',
		type: 'U16',
		gain: null,
		unit: '',
		perm: 'WO',
		desc: 'Start/Stop: 0=Stop, 1=Start',
	},
	{
		addr: 40001,
		qty: 2,
		name: 'plant.control.activePowerTarget',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		perm: 'RW',
		desc: 'Active power fixed adjustment target',
	},
	{
		addr: 40003,
		qty: 2,
		name: 'plant.control.reactivePowerTarget',
		type: 'S32',
		gain: 1000,
		unit: 'kVar',
		perm: 'RW',
		desc: 'Reactive power fixed adjustment target',
	},
	{
		addr: 40005,
		qty: 1,
		name: 'plant.control.activePowerPercent',
		type: 'S16',
		gain: 100,
		unit: '%',
		perm: 'RW',
		desc: 'Active power percentage adjustment [-100,100]',
	},
	{
		addr: 40006,
		qty: 1,
		name: 'plant.control.qsAdjustment',
		type: 'S16',
		gain: 100,
		unit: '%',
		perm: 'RW',
		desc: 'Q/S adjustment [-60,60]',
	},
	{
		addr: 40007,
		qty: 1,
		name: 'plant.control.powerFactor',
		type: 'S16',
		gain: 1000,
		unit: '',
		perm: 'RW',
		desc: 'Power factor adjustment',
	},
	{
		addr: 40029,
		qty: 1,
		name: 'plant.control.remoteEmsEnable',
		type: 'U16',
		gain: null,
		unit: '',
		perm: 'RW',
		desc: 'Remote EMS enable: 0=disabled, 1=enabled',
	},
	{
		addr: 40030,
		qty: 1,
		name: 'plant.control.independentPhaseEnable',
		type: 'U16',
		gain: null,
		unit: '',
		perm: 'RW',
		desc: 'Independent phase power control enable',
	},
	{
		addr: 40031,
		qty: 1,
		name: 'plant.control.remoteEmsMode',
		type: 'U16',
		gain: null,
		unit: '',
		perm: 'RW',
		desc: 'Remote EMS control mode (see Appendix 6)',
	},
	{
		addr: 40032,
		qty: 2,
		name: 'plant.control.essMaxChargingLimit',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		perm: 'RW',
		desc: 'ESS max charging limit',
	},
	{
		addr: 40034,
		qty: 2,
		name: 'plant.control.essMaxDischargingLimit',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		perm: 'RW',
		desc: 'ESS max discharging limit',
	},
	{
		addr: 40036,
		qty: 2,
		name: 'plant.control.pvMaxPowerLimit',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		perm: 'RW',
		desc: 'PV max power limit',
	},
	{
		addr: 40038,
		qty: 2,
		name: 'plant.control.gridMaxExportLimit',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		perm: 'RW',
		desc: 'Grid point maximum export limitation',
	},
	{
		addr: 40040,
		qty: 2,
		name: 'plant.control.gridMaxImportLimit',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		perm: 'RW',
		desc: 'Grid point maximum import limitation',
	},
	{
		addr: 40042,
		qty: 2,
		name: 'plant.control.pcsMaxExportLimit',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		perm: 'RW',
		desc: 'PCS maximum export limitation',
	},
	{
		addr: 40044,
		qty: 2,
		name: 'plant.control.pcsMaxImportLimit',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		perm: 'RW',
		desc: 'PCS maximum import limitation',
	},
];

// ============================================================
// Section 5.3 - Hybrid Inverter Running Info (Read-Only, slave 1-246)
// ============================================================
const INVERTER_READ_REGISTERS = [
	{
		addr: 30500,
		qty: 15,
		name: 'inverter.modelType',
		type: 'STRING',
		gain: null,
		unit: '',
		role: 'info.name',
		desc: 'Model type',
	},
	{
		addr: 30515,
		qty: 10,
		name: 'inverter.serialNumber',
		type: 'STRING',
		gain: null,
		unit: '',
		role: 'info.serial',
		desc: 'Serial number',
	},
	{
		addr: 30525,
		qty: 15,
		name: 'inverter.firmwareVersion',
		type: 'STRING',
		gain: null,
		unit: '',
		role: 'info.firmware',
		desc: 'Machine firmware version',
	},
	{
		addr: 30540,
		qty: 2,
		name: 'inverter.ratedActivePower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Rated active power',
	},
	{
		addr: 30542,
		qty: 2,
		name: 'inverter.maxApparentPower',
		type: 'U32',
		gain: 1000,
		unit: 'kVA',
		role: 'value.power',
		desc: 'Max apparent power',
	},
	{
		addr: 30544,
		qty: 2,
		name: 'inverter.maxActivePower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Max active power',
	},
	{
		addr: 30546,
		qty: 2,
		name: 'inverter.maxAbsorptionPower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Max absorption power',
	},
	{
		addr: 30548,
		qty: 2,
		name: 'inverter.ratedBatteryCapacity',
		type: 'U32',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'Rated battery capacity',
	},
	{
		addr: 30550,
		qty: 2,
		name: 'inverter.essRatedChargePower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'ESS rated charge power',
	},
	{
		addr: 30552,
		qty: 2,
		name: 'inverter.essRatedDischargePower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'ESS rated discharge power',
	},
	{
		addr: 30566,
		qty: 2,
		name: 'inverter.essDailyChargeEnergy',
		type: 'U32',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'ESS daily charge energy',
	},
	{
		addr: 30568,
		qty: 4,
		name: 'inverter.essAccumulatedChargeEnergy',
		type: 'U64',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'ESS accumulated charge energy',
	},
	{
		addr: 30572,
		qty: 2,
		name: 'inverter.essDailyDischargeEnergy',
		type: 'U32',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'ESS daily discharge energy',
	},
	{
		addr: 30574,
		qty: 4,
		name: 'inverter.essAccumulatedDischargeEnergy',
		type: 'U64',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'ESS accumulated discharge energy',
	},
	{
		addr: 30578,
		qty: 1,
		name: 'inverter.runningState',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'Running state (0=Standby,1=Running,2=Fault,3=Shutdown)',
	},
	{
		addr: 30579,
		qty: 2,
		name: 'inverter.maxActivePowerAdjust',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Max active power adjustment value',
	},
	{
		addr: 30581,
		qty: 2,
		name: 'inverter.minActivePowerAdjust',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Min active power adjustment value',
	},
	{
		addr: 30583,
		qty: 2,
		name: 'inverter.maxReactivePowerFeed',
		type: 'U32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Max reactive power fed to AC',
	},
	{
		addr: 30585,
		qty: 2,
		name: 'inverter.maxReactivePowerAbsorb',
		type: 'U32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Max reactive power absorbed from AC',
	},
	{
		addr: 30587,
		qty: 2,
		name: 'inverter.activePower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Active power',
	},
	{
		addr: 30589,
		qty: 2,
		name: 'inverter.reactivePower',
		type: 'S32',
		gain: 1000,
		unit: 'kVar',
		role: 'value.power',
		desc: 'Reactive power',
	},
	{
		addr: 30591,
		qty: 2,
		name: 'inverter.essMaxBatteryChargePower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'ESS max battery charge power',
	},
	{
		addr: 30593,
		qty: 2,
		name: 'inverter.essMaxBatteryDischargePower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'ESS max battery discharge power',
	},
	{
		addr: 30595,
		qty: 2,
		name: 'inverter.essAvailableBatteryChargeEnergy',
		type: 'U32',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'ESS available battery charge energy',
	},
	{
		addr: 30597,
		qty: 2,
		name: 'inverter.essAvailableBatteryDischargeEnergy',
		type: 'U32',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'ESS available battery discharge energy',
	},
	{
		addr: 30599,
		qty: 2,
		name: 'inverter.essChargeDischargePower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'ESS charge/discharge power',
	},
	{
		addr: 30601,
		qty: 1,
		name: 'inverter.essBatterySoc',
		type: 'U16',
		gain: 10,
		unit: '%',
		role: 'value.battery',
		desc: 'Battery SOC',
	},
	{
		addr: 30602,
		qty: 1,
		name: 'inverter.essBatterySoh',
		type: 'U16',
		gain: 10,
		unit: '%',
		role: 'value.battery',
		desc: 'Battery SOH',
	},
	{
		addr: 30603,
		qty: 1,
		name: 'inverter.essAvgCellTemperature',
		type: 'S16',
		gain: 10,
		unit: '°C',
		role: 'value.temperature',
		desc: 'Average cell temperature',
	},
	{
		addr: 30604,
		qty: 1,
		name: 'inverter.essAvgCellVoltage',
		type: 'U16',
		gain: 1000,
		unit: 'V',
		role: 'value.voltage',
		desc: 'Average cell voltage',
	},
	{
		addr: 30605,
		qty: 1,
		name: 'inverter.alarm1',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'Alarm 1 (PCS alarms Appendix 2)',
	},
	{
		addr: 30606,
		qty: 1,
		name: 'inverter.alarm2',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'Alarm 2 (PCS alarms Appendix 3)',
	},
	{
		addr: 30607,
		qty: 1,
		name: 'inverter.alarm3',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'Alarm 3 (ESS alarms Appendix 4)',
	},
	{
		addr: 30608,
		qty: 1,
		name: 'inverter.alarm4',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'Alarm 4 (Gateway alarms Appendix 5)',
	},
	{
		addr: 30609,
		qty: 1,
		name: 'inverter.alarm5',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'Alarm 5 (DC Charger alarms Appendix 11)',
	},
	{
		addr: 30620,
		qty: 1,
		name: 'inverter.essMaxBatteryTemperature',
		type: 'S16',
		gain: 10,
		unit: '°C',
		role: 'value.temperature',
		desc: 'Max battery cluster temperature',
	},
	{
		addr: 30621,
		qty: 1,
		name: 'inverter.essMinBatteryTemperature',
		type: 'S16',
		gain: 10,
		unit: '°C',
		role: 'value.temperature',
		desc: 'Min battery cluster temperature',
	},
	{
		addr: 30622,
		qty: 1,
		name: 'inverter.essMaxBatteryCellVoltage',
		type: 'U16',
		gain: 1000,
		unit: 'V',
		role: 'value.voltage',
		desc: 'Max battery cluster cell voltage',
	},
	{
		addr: 30623,
		qty: 1,
		name: 'inverter.essMinBatteryCellVoltage',
		type: 'U16',
		gain: 1000,
		unit: 'V',
		role: 'value.voltage',
		desc: 'Min battery cluster cell voltage',
	},
	{
		addr: 31000,
		qty: 1,
		name: 'inverter.ratedGridVoltage',
		type: 'U16',
		gain: 10,
		unit: 'V',
		role: 'value.voltage',
		desc: 'Rated grid voltage',
	},
	{
		addr: 31001,
		qty: 1,
		name: 'inverter.ratedGridFrequency',
		type: 'U16',
		gain: 100,
		unit: 'Hz',
		role: 'value.frequency',
		desc: 'Rated grid frequency',
	},
	{
		addr: 31002,
		qty: 1,
		name: 'inverter.gridFrequency',
		type: 'U16',
		gain: 100,
		unit: 'Hz',
		role: 'value.frequency',
		desc: 'Grid frequency',
	},
	{
		addr: 31003,
		qty: 1,
		name: 'inverter.pcsInternalTemp',
		type: 'S16',
		gain: 10,
		unit: '°C',
		role: 'value.temperature',
		desc: 'PCS internal temperature',
	},
	{
		addr: 31004,
		qty: 1,
		name: 'inverter.outputType',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'Output type: 0=L/N,1=L1/L2/L3,2=L1/L2/L3/N,3=L1/L2/N',
	},
	{
		addr: 31005,
		qty: 2,
		name: 'inverter.abLineVoltage',
		type: 'U32',
		gain: 100,
		unit: 'V',
		role: 'value.voltage',
		desc: 'A-B line voltage',
	},
	{
		addr: 31007,
		qty: 2,
		name: 'inverter.bcLineVoltage',
		type: 'U32',
		gain: 100,
		unit: 'V',
		role: 'value.voltage',
		desc: 'B-C line voltage',
	},
	{
		addr: 31009,
		qty: 2,
		name: 'inverter.caLineVoltage',
		type: 'U32',
		gain: 100,
		unit: 'V',
		role: 'value.voltage',
		desc: 'C-A line voltage',
	},
	{
		addr: 31011,
		qty: 2,
		name: 'inverter.phaseAVoltage',
		type: 'U32',
		gain: 100,
		unit: 'V',
		role: 'value.voltage',
		desc: 'Phase A voltage',
	},
	{
		addr: 31013,
		qty: 2,
		name: 'inverter.phaseBVoltage',
		type: 'U32',
		gain: 100,
		unit: 'V',
		role: 'value.voltage',
		desc: 'Phase B voltage',
	},
	{
		addr: 31015,
		qty: 2,
		name: 'inverter.phaseCVoltage',
		type: 'U32',
		gain: 100,
		unit: 'V',
		role: 'value.voltage',
		desc: 'Phase C voltage',
	},
	{
		addr: 31017,
		qty: 2,
		name: 'inverter.phaseACurrent',
		type: 'S32',
		gain: 100,
		unit: 'A',
		role: 'value.current',
		desc: 'Phase A current',
	},
	{
		addr: 31019,
		qty: 2,
		name: 'inverter.phaseBCurrent',
		type: 'S32',
		gain: 100,
		unit: 'A',
		role: 'value.current',
		desc: 'Phase B current',
	},
	{
		addr: 31021,
		qty: 2,
		name: 'inverter.phaseCCurrent',
		type: 'S32',
		gain: 100,
		unit: 'A',
		role: 'value.current',
		desc: 'Phase C current',
	},
	{
		addr: 31023,
		qty: 1,
		name: 'inverter.powerFactor',
		type: 'U16',
		gain: 1000,
		unit: '',
		role: 'value',
		desc: 'Power factor',
	},
	{
		addr: 31024,
		qty: 1,
		name: 'inverter.packCount',
		type: 'U16',
		gain: 1,
		unit: '',
		role: 'value',
		desc: 'PACK count',
	},
	{
		addr: 31025,
		qty: 1,
		name: 'inverter.pvStringCount',
		type: 'U16',
		gain: 1,
		unit: '',
		role: 'value',
		desc: 'PV string count',
	},
	{
		addr: 31026,
		qty: 1,
		name: 'inverter.mpptCount',
		type: 'U16',
		gain: 1,
		unit: '',
		role: 'value',
		desc: 'MPPT count',
	},
	{
		addr: 31027,
		qty: 1,
		name: 'inverter.pv1Voltage',
		type: 'S16',
		gain: 10,
		unit: 'V',
		role: 'value.voltage',
		desc: 'PV1 voltage',
	},
	{
		addr: 31028,
		qty: 1,
		name: 'inverter.pv1Current',
		type: 'S16',
		gain: 100,
		unit: 'A',
		role: 'value.current',
		desc: 'PV1 current',
	},
	{
		addr: 31029,
		qty: 1,
		name: 'inverter.pv2Voltage',
		type: 'S16',
		gain: 10,
		unit: 'V',
		role: 'value.voltage',
		desc: 'PV2 voltage',
	},
	{
		addr: 31030,
		qty: 1,
		name: 'inverter.pv2Current',
		type: 'S16',
		gain: 100,
		unit: 'A',
		role: 'value.current',
		desc: 'PV2 current',
	},
	{
		addr: 31031,
		qty: 1,
		name: 'inverter.pv3Voltage',
		type: 'S16',
		gain: 10,
		unit: 'V',
		role: 'value.voltage',
		desc: 'PV3 voltage',
	},
	{
		addr: 31032,
		qty: 1,
		name: 'inverter.pv3Current',
		type: 'S16',
		gain: 100,
		unit: 'A',
		role: 'value.current',
		desc: 'PV3 current',
	},
	{
		addr: 31033,
		qty: 1,
		name: 'inverter.pv4Voltage',
		type: 'S16',
		gain: 10,
		unit: 'V',
		role: 'value.voltage',
		desc: 'PV4 voltage',
	},
	{
		addr: 31034,
		qty: 1,
		name: 'inverter.pv4Current',
		type: 'S16',
		gain: 100,
		unit: 'A',
		role: 'value.current',
		desc: 'PV4 current',
	},
	{
		addr: 31035,
		qty: 2,
		name: 'inverter.pvPower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'PV power',
	},
	{
		addr: 31037,
		qty: 1,
		name: 'inverter.insulationResistance',
		type: 'U16',
		gain: 1000,
		unit: 'MΩ',
		role: 'value',
		desc: 'Insulation resistance',
	},
	{
		addr: 31038,
		qty: 2,
		name: 'inverter.startupTime',
		type: 'U32',
		gain: 1,
		unit: 's',
		role: 'value.time',
		desc: 'Startup time (epoch)',
	},
	{
		addr: 31040,
		qty: 2,
		name: 'inverter.shutdownTime',
		type: 'U32',
		gain: 1,
		unit: 's',
		role: 'value.time',
		desc: 'Shutdown time (epoch)',
	},
];

// ============================================================
// Section 5.4 - Hybrid Inverter Parameter Setting (Holding, slave 1-246)
// ============================================================
const INVERTER_WRITE_REGISTERS = [
	{
		addr: 40500,
		qty: 1,
		name: 'inverter.control.startStop',
		type: 'U16',
		gain: null,
		unit: '',
		perm: 'WO',
		desc: 'Start/Stop: 0=Stop, 1=Start',
	},
	{
		addr: 40501,
		qty: 1,
		name: 'inverter.control.gridCode',
		type: 'U16',
		gain: null,
		unit: '',
		perm: 'RW',
		desc: 'Grid code',
	},
	{
		addr: 41500,
		qty: 1,
		name: 'inverter.control.remoteEmsDispatchEnable',
		type: 'U16',
		gain: null,
		unit: '',
		perm: 'RW',
		desc: 'Remote EMS dispatch enable',
	},
	{
		addr: 41501,
		qty: 2,
		name: 'inverter.control.activePowerFixed',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		perm: 'RW',
		desc: 'Active power fixed value adjustment',
	},
	{
		addr: 41503,
		qty: 2,
		name: 'inverter.control.reactivePowerFixed',
		type: 'S32',
		gain: 1000,
		unit: 'kVar',
		perm: 'RW',
		desc: 'Reactive power fixed value adjustment',
	},
	{
		addr: 41505,
		qty: 1,
		name: 'inverter.control.activePowerPercent',
		type: 'S16',
		gain: 100,
		unit: '%',
		perm: 'RW',
		desc: 'Active power percentage adjustment',
	},
	{
		addr: 41506,
		qty: 1,
		name: 'inverter.control.reactivePowerQS',
		type: 'S16',
		gain: 100,
		unit: '%',
		perm: 'RW',
		desc: 'Reactive power Q/S adjustment',
	},
	{
		addr: 41507,
		qty: 1,
		name: 'inverter.control.powerFactor',
		type: 'S16',
		gain: 1000,
		unit: '',
		perm: 'RW',
		desc: 'Power factor adjustment',
	},
];

// DC Charger write registers
const DC_CHARGER_WRITE_REGISTERS = [
	{
		addr: 41000,
		qty: 1,
		name: 'dcCharger.control.startStop',
		type: 'U16',
		gain: null,
		unit: '',
		perm: 'WO',
		desc: 'Start/Stop: 0=Start, 1=Stop',
	},
];

// ============================================================
// Section 5.5 - AC-Charger Running Info (Read-Only, slave 1-246)
// ============================================================
const AC_CHARGER_READ_REGISTERS = [
	{
		addr: 32000,
		qty: 1,
		name: 'acCharger.systemState',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'System state (IEC61851-1)',
	},
	{
		addr: 32001,
		qty: 2,
		name: 'acCharger.totalEnergyConsumed',
		type: 'U32',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'Total energy consumed',
	},
	{
		addr: 32003,
		qty: 2,
		name: 'acCharger.chargingPower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Charging power',
	},
	{
		addr: 32005,
		qty: 2,
		name: 'acCharger.ratedPower',
		type: 'U32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Rated power',
	},
	{
		addr: 32007,
		qty: 2,
		name: 'acCharger.ratedCurrent',
		type: 'S32',
		gain: 100,
		unit: 'A',
		role: 'value.current',
		desc: 'Rated current',
	},
	{
		addr: 32009,
		qty: 1,
		name: 'acCharger.ratedVoltage',
		type: 'U16',
		gain: 10,
		unit: 'V',
		role: 'value.voltage',
		desc: 'Rated voltage',
	},
	{
		addr: 32010,
		qty: 2,
		name: 'acCharger.inputBreakerRatedCurrent',
		type: 'S32',
		gain: 100,
		unit: 'A',
		role: 'value.current',
		desc: 'AC-Charger input breaker rated current',
	},
	{
		addr: 32012,
		qty: 1,
		name: 'acCharger.alarm1',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'Alarm 1 (Appendix 8)',
	},
	{
		addr: 32013,
		qty: 1,
		name: 'acCharger.alarm2',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'Alarm 2 (Appendix 9)',
	},
	{
		addr: 32014,
		qty: 1,
		name: 'acCharger.alarm3',
		type: 'U16',
		gain: null,
		unit: '',
		role: 'value',
		desc: 'Alarm 3 (Appendix 10)',
	},
];

// ============================================================
// Section 5.6 - AC-Charger Parameter Setting (Holding, slave 1-246)
// ============================================================
const AC_CHARGER_WRITE_REGISTERS = [
	{
		addr: 42000,
		qty: 1,
		name: 'acCharger.control.startStop',
		type: 'U16',
		gain: null,
		unit: '',
		perm: 'WO',
		desc: 'Start/Stop: 0=Start, 1=Stop',
	},
	{
		addr: 42001,
		qty: 2,
		name: 'acCharger.control.outputCurrent',
		type: 'U32',
		gain: 100,
		unit: 'A',
		perm: 'RW',
		desc: 'Charger output current [6, rated]',
	},
];

// DC Charger reading registers (part of inverter slave)
const DC_CHARGER_READ_REGISTERS = [
	{
		addr: 31500,
		qty: 1,
		name: 'dcCharger.vehicleBatteryVoltage',
		type: 'U16',
		gain: 10,
		unit: 'V',
		role: 'value.voltage',
		desc: 'Vehicle battery voltage',
	},
	{
		addr: 31501,
		qty: 1,
		name: 'dcCharger.chargingCurrent',
		type: 'U16',
		gain: 10,
		unit: 'A',
		role: 'value.current',
		desc: 'Charging current',
	},
	{
		addr: 31502,
		qty: 2,
		name: 'dcCharger.outputPower',
		type: 'S32',
		gain: 1000,
		unit: 'kW',
		role: 'value.power',
		desc: 'Output power',
	},
	{
		addr: 31504,
		qty: 1,
		name: 'dcCharger.vehicleSoc',
		type: 'U16',
		gain: 10,
		unit: '%',
		role: 'value.battery',
		desc: 'Vehicle SOC',
	},
	{
		addr: 31505,
		qty: 2,
		name: 'dcCharger.currentChargingCapacity',
		type: 'U32',
		gain: 100,
		unit: 'kWh',
		role: 'value.energy',
		desc: 'Current charging capacity (single session)',
	},
	{
		addr: 31507,
		qty: 2,
		name: 'dcCharger.currentChargingDuration',
		type: 'U32',
		gain: 1,
		unit: 's',
		role: 'value.time',
		desc: 'Current charging duration (single session)',
	},
];

// Running state values
const RUNNING_STATES = {
	0x00: 'Standby',
	0x01: 'Running',
	0x02: 'Fault',
	0x03: 'Shutdown',
};

// EMS work modes
const EMS_WORK_MODES = {
	0: 'Max Self Consumption',
	1: 'AI Mode',
	2: 'TOU',
	7: 'Remote EMS',
};

// Remote EMS control modes
const REMOTE_EMS_MODES = {
	0x00: 'PCS Remote Control',
	0x01: 'Standby',
	0x02: 'Maximum Self-Consumption',
	0x03: 'Command Charging (Grid First)',
	0x04: 'Command Charging (PV First)',
	0x05: 'Command Discharging (PV First)',
	0x06: 'Command Discharging (ESS First)',
};

module.exports = {
	PLANT_READ_REGISTERS,
	PLANT_WRITE_REGISTERS,
	INVERTER_READ_REGISTERS,
	INVERTER_WRITE_REGISTERS,
	DC_CHARGER_READ_REGISTERS,
	DC_CHARGER_WRITE_REGISTERS,
	AC_CHARGER_READ_REGISTERS,
	AC_CHARGER_WRITE_REGISTERS,
	RUNNING_STATES,
	EMS_WORK_MODES,
	REMOTE_EMS_MODES,
};
