'use strict';

/**
 * Sigenergy Modbus V2.9 Register Definitions
 * Based on official Sigenergy Modbus Protocol V2.9
 */

// ============================================================
// Section 5.1 - Plant Running Information (Read-Only, slave 247)
// ============================================================
const PLANT_READ_REGISTERS = [
    {
        addr: 30000,
        qty: 2,
        name: 'plant.systemTime',
        type: 'U32',
        gain: 1,
        unit: 's',
        role: 'value.time',
        desc: 'System time (Epoch seconds)',
    },
    {
        addr: 30002,
        qty: 1,
        name: 'plant.systemTimeZone',
        type: 'S16',
        gain: 1,
        unit: 'min',
        role: 'value',
        desc: 'System time zone offset (minutes)',
    },
    {
        addr: 30003,
        qty: 1,
        name: 'plant.emsWorkMode',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'EMS work mode: 0=MaxSelfConsumption,1=AI,2=TOU,7=RemoteEMS',
    },
    {
        addr: 30004,
        qty: 1,
        name: 'plant.gridSensorStatus',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'indicator',
        desc: 'Grid sensor status: 0=disconnected, 1=connected',
    },
    {
        addr: 30005,
        qty: 2,
        name: 'plant.gridActivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Grid active power (>0 buy, <0 sell)',
    },
    {
        addr: 30007,
        qty: 2,
        name: 'plant.gridReactivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Grid reactive power',
    },
    {
        addr: 30009,
        qty: 1,
        name: 'plant.onOffGridStatus',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'On/Off grid: 0=on,1=off(auto),2=off(manual)',
    },
    {
        addr: 30010,
        qty: 2,
        name: 'plant.maxActivePower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Max active power (base value)',
    },
    {
        addr: 30012,
        qty: 2,
        name: 'plant.maxApparentPower',
        type: 'U32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Max apparent power (base value)',
    },
    {
        addr: 30014,
        qty: 1,
        name: 'plant.essSoc',
        type: 'U16',
        gain: 10,
        unit: '%',
        role: 'value.battery',
        desc: 'ESS State of Charge',
    },
    {
        addr: 30015,
        qty: 2,
        name: 'plant.phaseAActivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Plant phase A active power',
    },
    {
        addr: 30017,
        qty: 2,
        name: 'plant.phaseBActivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Plant phase B active power',
    },
    {
        addr: 30019,
        qty: 2,
        name: 'plant.phaseCActivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Plant phase C active power',
    },
    {
        addr: 30021,
        qty: 2,
        name: 'plant.phaseAReactivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Plant phase A reactive power',
    },
    {
        addr: 30023,
        qty: 2,
        name: 'plant.phaseBReactivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Plant phase B reactive power',
    },
    {
        addr: 30025,
        qty: 2,
        name: 'plant.phaseCReactivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Plant phase C reactive power',
    },
    {
        addr: 30027,
        qty: 1,
        name: 'plant.generalAlarm1',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'General Alarm 1 (PCS alarms, see Appendix 2)',
    },
    {
        addr: 30028,
        qty: 1,
        name: 'plant.generalAlarm2',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'General Alarm 2 (PCS alarms, see Appendix 3)',
    },
    {
        addr: 30029,
        qty: 1,
        name: 'plant.generalAlarm3',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'General Alarm 3 (ESS alarms, see Appendix 4)',
    },
    {
        addr: 30030,
        qty: 1,
        name: 'plant.generalAlarm4',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'General Alarm 4 (Gateway alarms, see Appendix 5)',
    },
    {
        addr: 30031,
        qty: 2,
        name: 'plant.activePower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Plant active power',
    },
    {
        addr: 30033,
        qty: 2,
        name: 'plant.reactivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Plant reactive power',
    },
    {
        addr: 30035,
        qty: 2,
        name: 'plant.pvPower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Photovoltaic power',
    },
    {
        addr: 30037,
        qty: 2,
        name: 'plant.essPower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'ESS power (<0=discharging, >0=charging)',
    },
    {
        addr: 30039,
        qty: 2,
        name: 'plant.availableMaxActivePower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Available max active power',
    },
    {
        addr: 30041,
        qty: 2,
        name: 'plant.availableMinActivePower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Available min active power (absorption)',
    },
    {
        addr: 30043,
        qty: 2,
        name: 'plant.availableMaxReactivePower',
        type: 'U32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Available max reactive power',
    },
    {
        addr: 30045,
        qty: 2,
        name: 'plant.availableMinReactivePower',
        type: 'U32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Available min reactive power',
    },
    {
        addr: 30047,
        qty: 2,
        name: 'plant.essAvailableMaxChargingPower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'ESS available max charging power',
    },
    {
        addr: 30049,
        qty: 2,
        name: 'plant.essAvailableMaxDischargingPower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'ESS available max discharging power',
    },
    {
        addr: 30051,
        qty: 1,
        name: 'plant.runningState',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Plant running state (0=Standby,1=Running,2=Fault,3=Shutdown)',
    },
    {
        addr: 30052,
        qty: 2,
        name: 'plant.gridPhaseAActivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Grid sensor Phase A active power',
    },
    {
        addr: 30054,
        qty: 2,
        name: 'plant.gridPhaseBActivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Grid sensor Phase B active power',
    },
    {
        addr: 30056,
        qty: 2,
        name: 'plant.gridPhaseCActivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Grid sensor Phase C active power',
    },
    {
        addr: 30058,
        qty: 2,
        name: 'plant.gridPhaseAReactivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Grid sensor Phase A reactive power',
    },
    {
        addr: 30060,
        qty: 2,
        name: 'plant.gridPhaseBReactivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Grid sensor Phase B reactive power',
    },
    {
        addr: 30062,
        qty: 2,
        name: 'plant.gridPhaseCReactivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Grid sensor Phase C reactive power',
    },
    {
        addr: 30064,
        qty: 2,
        name: 'plant.essAvailableMaxChargingCapacity',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'ESS available max charging capacity',
    },
    {
        addr: 30066,
        qty: 2,
        name: 'plant.essAvailableMaxDischargingCapacity',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'ESS available max discharging capacity',
    },
    {
        addr: 30068,
        qty: 2,
        name: 'plant.essRatedChargingPower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'ESS rated charging power',
    },
    {
        addr: 30070,
        qty: 2,
        name: 'plant.essRatedDischargingPower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'ESS rated discharging power',
    },
    {
        addr: 30072,
        qty: 1,
        name: 'plant.generalAlarm5',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'General Alarm 5 (DC Charger alarms, see Appendix 11)',
    },
    {
        addr: 30083,
        qty: 2,
        name: 'plant.essRatedEnergyCapacity',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'ESS rated energy capacity',
    },
    {
        addr: 30085,
        qty: 1,
        name: 'plant.essChargeSOC',
        type: 'U16',
        gain: 10,
        unit: '%',
        role: 'value.battery',
        desc: 'ESS charge cut-off SOC',
    },
    {
        addr: 30086,
        qty: 1,
        name: 'plant.essDischargeSOC',
        type: 'U16',
        gain: 10,
        unit: '%',
        role: 'value.battery',
        desc: 'ESS discharge cut-off SOC',
    },
    {
        addr: 30087,
        qty: 1,
        name: 'plant.essSoh',
        type: 'U16',
        gain: 10,
        unit: '%',
        role: 'value.battery',
        desc: 'ESS State of Health (weighted average)',
    },
    // V2.6 — plant statistics (continuous with 30087, same FC04 group)
    {
        addr: 30088,
        qty: 4,
        name: 'plant.statistics.plantPvTotalGeneration',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Plant PV total generation (V2.6)',
    },
    {
        addr: 30092,
        qty: 2,
        name: 'plant.statistics.totalLoadDailyConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total load daily consumption (V2.6)',
    },
    {
        addr: 30094,
        qty: 4,
        name: 'plant.statistics.totalLoadConsumption',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total load consumption (V2.6)',
    },
    // V2.6 — smart loads 1–24 total consumption (feature flag: enableSmartLoads)
    {
        addr: 30098,
        qty: 2,
        name: 'plant.smartLoad.1.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 1 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30100,
        qty: 2,
        name: 'plant.smartLoad.2.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 2 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30102,
        qty: 2,
        name: 'plant.smartLoad.3.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 3 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30104,
        qty: 2,
        name: 'plant.smartLoad.4.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 4 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30106,
        qty: 2,
        name: 'plant.smartLoad.5.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 5 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30108,
        qty: 2,
        name: 'plant.smartLoad.6.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 6 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30110,
        qty: 2,
        name: 'plant.smartLoad.7.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 7 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30112,
        qty: 2,
        name: 'plant.smartLoad.8.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 8 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30114,
        qty: 2,
        name: 'plant.smartLoad.9.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 9 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30116,
        qty: 2,
        name: 'plant.smartLoad.10.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 10 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30118,
        qty: 2,
        name: 'plant.smartLoad.11.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 11 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30120,
        qty: 2,
        name: 'plant.smartLoad.12.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 12 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30122,
        qty: 2,
        name: 'plant.smartLoad.13.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 13 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30124,
        qty: 2,
        name: 'plant.smartLoad.14.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 14 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30126,
        qty: 2,
        name: 'plant.smartLoad.15.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 15 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30128,
        qty: 2,
        name: 'plant.smartLoad.16.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 16 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30130,
        qty: 2,
        name: 'plant.smartLoad.17.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 17 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30132,
        qty: 2,
        name: 'plant.smartLoad.18.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 18 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30134,
        qty: 2,
        name: 'plant.smartLoad.19.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 19 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30136,
        qty: 2,
        name: 'plant.smartLoad.20.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 20 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30138,
        qty: 2,
        name: 'plant.smartLoad.21.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 21 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30140,
        qty: 2,
        name: 'plant.smartLoad.22.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 22 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30142,
        qty: 2,
        name: 'plant.smartLoad.23.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 23 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30144,
        qty: 2,
        name: 'plant.smartLoad.24.totalConsumption',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Smart load 24 total consumption (V2.6)',
        feature: 'enableSmartLoads',
    },
    // V2.6 — smart loads 1–24 power (feature flag: enableSmartLoads)
    {
        addr: 30146,
        qty: 2,
        name: 'plant.smartLoad.1.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 1 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30148,
        qty: 2,
        name: 'plant.smartLoad.2.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 2 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30150,
        qty: 2,
        name: 'plant.smartLoad.3.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 3 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30152,
        qty: 2,
        name: 'plant.smartLoad.4.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 4 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30154,
        qty: 2,
        name: 'plant.smartLoad.5.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 5 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30156,
        qty: 2,
        name: 'plant.smartLoad.6.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 6 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30158,
        qty: 2,
        name: 'plant.smartLoad.7.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 7 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30160,
        qty: 2,
        name: 'plant.smartLoad.8.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 8 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30162,
        qty: 2,
        name: 'plant.smartLoad.9.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 9 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30164,
        qty: 2,
        name: 'plant.smartLoad.10.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 10 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30166,
        qty: 2,
        name: 'plant.smartLoad.11.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 11 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30168,
        qty: 2,
        name: 'plant.smartLoad.12.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 12 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30170,
        qty: 2,
        name: 'plant.smartLoad.13.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 13 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30172,
        qty: 2,
        name: 'plant.smartLoad.14.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 14 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30174,
        qty: 2,
        name: 'plant.smartLoad.15.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 15 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30176,
        qty: 2,
        name: 'plant.smartLoad.16.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 16 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30178,
        qty: 2,
        name: 'plant.smartLoad.17.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 17 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30180,
        qty: 2,
        name: 'plant.smartLoad.18.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 18 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30182,
        qty: 2,
        name: 'plant.smartLoad.19.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 19 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30184,
        qty: 2,
        name: 'plant.smartLoad.20.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 20 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30186,
        qty: 2,
        name: 'plant.smartLoad.21.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 21 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30188,
        qty: 2,
        name: 'plant.smartLoad.22.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 22 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30190,
        qty: 2,
        name: 'plant.smartLoad.23.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 23 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    {
        addr: 30192,
        qty: 2,
        name: 'plant.smartLoad.24.power',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Smart load 24 power (V2.6)',
        feature: 'enableSmartLoads',
    },
    // V2.7/V2.8 — cumulative energy statistics (feature flag: enableCumulativeEnergy)
    {
        addr: 30194,
        qty: 2,
        name: 'plant.statistics.thirdPartyInverterPower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Third party inverter active power (V2.7)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30196,
        qty: 4,
        name: 'plant.statistics.legacy.totalGeneration3rdParty',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total 3rd party generation — legacy interface (V2.7)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30200,
        qty: 4,
        name: 'plant.statistics.legacy.totalEssCharged',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total ESS charged — legacy interface (V2.7)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30204,
        qty: 4,
        name: 'plant.statistics.legacy.totalEssDischarged',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total ESS discharged — legacy interface (V2.7)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30208,
        qty: 4,
        name: 'plant.statistics.legacy.totalEvdcCharged',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total EVDC charged — legacy interface (V2.7)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30212,
        qty: 4,
        name: 'plant.statistics.legacy.totalEvdcDischarged',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total EVDC discharged — legacy interface (V2.7)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30216,
        qty: 4,
        name: 'plant.statistics.legacy.totalImportedEnergy',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total imported energy — legacy interface (V2.7)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30220,
        qty: 4,
        name: 'plant.statistics.legacy.totalExportedEnergy',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total exported energy — legacy interface (V2.7)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30224,
        qty: 4,
        name: 'plant.statistics.legacy.totalOilGeneratorEnergy',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total oil generator energy — legacy interface (V2.7)',
        feature: 'enableCumulativeEnergy',
    },
    // V2.8 — new statistics interface
    {
        addr: 30228,
        qty: 4,
        name: 'plant.statistics.totalCommonLoadsConsumption',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total common loads consumption (V2.8)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30232,
        qty: 4,
        name: 'plant.statistics.totalEvacCharged',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total EVAC charged (V2.8)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30236,
        qty: 4,
        name: 'plant.statistics.totalSelfPvGeneration',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total self PV generation (V2.8)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30240,
        qty: 4,
        name: 'plant.statistics.totalGeneration3rdParty',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total 3rd party generation (V2.8)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30244,
        qty: 4,
        name: 'plant.statistics.totalEssCharged',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total ESS charged (V2.8)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30248,
        qty: 4,
        name: 'plant.statistics.totalEssDischarged',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total ESS discharged (V2.8)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30252,
        qty: 4,
        name: 'plant.statistics.totalEvdcCharged',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total EVDC charged (V2.8)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30256,
        qty: 4,
        name: 'plant.statistics.totalEvdcDischarged',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total EVDC discharged (V2.8)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30260,
        qty: 4,
        name: 'plant.statistics.totalImportedEnergy',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total imported energy (V2.8)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30264,
        qty: 4,
        name: 'plant.statistics.totalExportedEnergy',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total exported energy (V2.8)',
        feature: 'enableCumulativeEnergy',
    },
    {
        addr: 30268,
        qty: 4,
        name: 'plant.statistics.totalOilGeneratorEnergy',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total oil generator energy (V2.8)',
        feature: 'enableCumulativeEnergy',
    },
    // V2.8 — separate FC04 group (gap > 4 from 30087)
    {
        addr: 30272,
        qty: 2,
        name: 'plant.pvTotalDailyGeneration',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'PV total daily generation (V2.8)',
    },
    {
        addr: 30274,
        qty: 2,
        name: 'plant.pvTotalGenerationPrevDay',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'PV total generation previous day (V2.8)',
    },
    // V2.9
    {
        addr: 30276,
        qty: 1,
        name: 'plant.gridCodeRatedFrequency',
        type: 'U16',
        gain: 100,
        unit: 'Hz',
        role: 'value.frequency',
        desc: 'Grid code rated frequency (V2.9)',
    },
    {
        addr: 30277,
        qty: 2,
        name: 'plant.gridCodeRatedVoltage',
        type: 'U32',
        gain: 100,
        unit: 'V',
        role: 'value.voltage',
        desc: 'Grid code rated voltage (V2.9)',
    },
    {
        addr: 30280,
        qty: 1,
        name: 'plant.mergedAlarm6',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Merged alarm 6 (V2.9)',
    },
    {
        addr: 30281,
        qty: 1,
        name: 'plant.mergedAlarm7',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Merged alarm 7 (V2.9)',
    },
    {
        addr: 30282,
        qty: 2,
        name: 'plant.generalLoadPower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'General load power (V2.9)',
    },
    {
        addr: 30284,
        qty: 2,
        name: 'plant.totalLoadPower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Total load power (V2.9)',
    },
    {
        addr: 30286,
        qty: 1,
        name: 'plant.essAvgCellTemperature',
        type: 'S16',
        gain: 10,
        unit: '°C',
        role: 'value.temperature',
        desc: 'ESS average cell temperature (V2.9)',
    },
];

// ============================================================
// Section 5.2 - Plant Parameter Setting (Holding, slave 0 or 247)
// ============================================================
const PLANT_WRITE_REGISTERS = [
    {
        addr: 40000,
        qty: 1,
        name: 'plant.control.startStop',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'WO',
        desc: 'Start/Stop: 0=Stop, 1=Start',
    },
    {
        addr: 40001,
        qty: 2,
        name: 'plant.control.activePowerTarget',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        perm: 'RW',
        desc: 'Active power fixed adjustment target',
    },
    {
        addr: 40003,
        qty: 2,
        name: 'plant.control.reactivePowerTarget',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        perm: 'RW',
        desc: 'Reactive power fixed adjustment target',
    },
    {
        addr: 40005,
        qty: 1,
        name: 'plant.control.activePowerPercent',
        type: 'S16',
        gain: 100,
        unit: '%',
        perm: 'RW',
        desc: 'Active power percentage adjustment [-100,100]',
    },
    {
        addr: 40006,
        qty: 1,
        name: 'plant.control.qsAdjustment',
        type: 'S16',
        gain: 100,
        unit: '%',
        perm: 'RW',
        desc: 'Q/S adjustment [-60,60]',
    },
    {
        addr: 40007,
        qty: 1,
        name: 'plant.control.powerFactor',
        type: 'S16',
        gain: 1000,
        unit: '',
        perm: 'RW',
        desc: 'Power factor adjustment',
    },
    {
        addr: 40029,
        qty: 1,
        name: 'plant.control.remoteEmsEnable',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'RW',
        desc: 'Remote EMS enable: 0=disabled, 1=enabled',
    },
    {
        addr: 40030,
        qty: 1,
        name: 'plant.control.independentPhaseEnable',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'RW',
        desc: 'Independent phase power control enable',
    },
    {
        addr: 40031,
        qty: 1,
        name: 'plant.control.remoteEmsMode',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'RW',
        desc: 'Remote EMS control mode (see Appendix 6)',
    },
    {
        addr: 40032,
        qty: 2,
        name: 'plant.control.essMaxChargingLimit',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        perm: 'RW',
        desc: 'ESS max charging limit',
    },
    {
        addr: 40034,
        qty: 2,
        name: 'plant.control.essMaxDischargingLimit',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        perm: 'RW',
        desc: 'ESS max discharging limit',
    },
    {
        addr: 40036,
        qty: 2,
        name: 'plant.control.pvMaxPowerLimit',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        perm: 'RW',
        desc: 'PV max power limit',
    },
    {
        addr: 40038,
        qty: 2,
        name: 'plant.control.gridMaxExportLimit',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        perm: 'RW',
        desc: 'Grid point maximum export limitation',
    },
    {
        addr: 40040,
        qty: 2,
        name: 'plant.control.gridMaxImportLimit',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        perm: 'RW',
        desc: 'Grid point maximum import limitation',
    },
    {
        addr: 40042,
        qty: 2,
        name: 'plant.control.pcsMaxExportLimit',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        perm: 'RW',
        desc: 'PCS maximum export limitation',
    },
    {
        addr: 40044,
        qty: 2,
        name: 'plant.control.pcsMaxImportLimit',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        perm: 'RW',
        desc: 'PCS maximum import limitation',
    },
    // V2.6 — ESS SOC settings
    {
        addr: 40046,
        qty: 1,
        name: 'plant.control.essBackupSoc',
        type: 'U16',
        gain: 10,
        unit: '%',
        perm: 'RW',
        desc: 'ESS backup SOC (V2.6)',
    },
    {
        addr: 40047,
        qty: 1,
        name: 'plant.control.essChargeCtOffSoc',
        type: 'U16',
        gain: 10,
        unit: '%',
        perm: 'RW',
        desc: 'ESS charge cut-off SOC (V2.6)',
    },
    {
        addr: 40048,
        qty: 1,
        name: 'plant.control.essDischargeCtOffSoc',
        type: 'U16',
        gain: 10,
        unit: '%',
        perm: 'RW',
        desc: 'ESS discharge cut-off SOC (V2.6)',
    },
    // V2.8 — active power regulation gradient + grid code settings (feature flag: enableGridCode)
    {
        addr: 40049,
        qty: 2,
        name: 'plant.gridCode.activePowerRegulationGradient',
        type: 'U32',
        gain: 1000,
        unit: '%/s',
        perm: 'RW',
        desc: 'Active power regulation gradient (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40051,
        qty: 1,
        name: 'plant.gridCode.lvrtEnable',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'RW',
        desc: 'LVRT enable (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40052,
        qty: 1,
        name: 'plant.gridCode.lvrtReactivePowerFactor',
        type: 'U16',
        gain: 100,
        unit: '%',
        perm: 'RW',
        desc: 'LVRT reactive power factor (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40053,
        qty: 1,
        name: 'plant.gridCode.lvrtNegSeqReactivePowerFactor',
        type: 'U16',
        gain: 100,
        unit: '%',
        perm: 'RW',
        desc: 'LVRT negative sequence reactive power factor (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40054,
        qty: 1,
        name: 'plant.gridCode.lvrtMode',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'RW',
        desc: 'LVRT mode (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40055,
        qty: 1,
        name: 'plant.gridCode.lvrtGridVoltageProtBlocking',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'RW',
        desc: 'LVRT grid voltage protection blocking (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40056,
        qty: 1,
        name: 'plant.gridCode.hvrtEnable',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'RW',
        desc: 'HVRT enable (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40057,
        qty: 1,
        name: 'plant.gridCode.hvrtReactivePowerFactor',
        type: 'U16',
        gain: 100,
        unit: '%',
        perm: 'RW',
        desc: 'HVRT reactive power factor (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40058,
        qty: 1,
        name: 'plant.gridCode.hvrtNegSeqReactivePowerFactor',
        type: 'U16',
        gain: 100,
        unit: '%',
        perm: 'RW',
        desc: 'HVRT negative sequence reactive power factor (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40059,
        qty: 1,
        name: 'plant.gridCode.hvrtMode',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'RW',
        desc: 'HVRT mode (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40060,
        qty: 1,
        name: 'plant.gridCode.hvrtGridVoltageProtBlocking',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'RW',
        desc: 'HVRT grid voltage protection blocking (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40061,
        qty: 1,
        name: 'plant.gridCode.overfreqDeratingEnable',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'RW',
        desc: 'Over-frequency derating enable (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40062,
        qty: 1,
        name: 'plant.gridCode.overfreqDeratingPowerRampRate',
        type: 'U16',
        gain: 100,
        unit: '%',
        perm: 'RW',
        desc: 'Over-frequency derating power ramp rate (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40063,
        qty: 1,
        name: 'plant.gridCode.overfreqDeratingTriggerFreq',
        type: 'U16',
        gain: 100,
        unit: 'Hz',
        perm: 'RW',
        desc: 'Over-frequency derating trigger frequency (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40064,
        qty: 1,
        name: 'plant.gridCode.overfreqDeratingCutOffFreq',
        type: 'U16',
        gain: 100,
        unit: 'Hz',
        perm: 'RW',
        desc: 'Over-frequency derating cut-off frequency (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40065,
        qty: 1,
        name: 'plant.gridCode.underfreqPowerBoostEnable',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'RW',
        desc: 'Under-frequency power boost enable (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40066,
        qty: 1,
        name: 'plant.gridCode.underfreqPowerBoostRampRate',
        type: 'U16',
        gain: 100,
        unit: '%',
        perm: 'RW',
        desc: 'Under-frequency power boost ramp rate (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40067,
        qty: 1,
        name: 'plant.gridCode.underfreqPowerBoostTriggerFreq',
        type: 'U16',
        gain: 100,
        unit: 'Hz',
        perm: 'RW',
        desc: 'Under-frequency power boost trigger frequency (V2.8)',
        feature: 'enableGridCode',
    },
    {
        addr: 40068,
        qty: 1,
        name: 'plant.gridCode.underfreqPowerBoostCutOffFreq',
        type: 'U16',
        gain: 100,
        unit: 'Hz',
        perm: 'RW',
        desc: 'Under-frequency power boost cut-off frequency (V2.8)',
        feature: 'enableGridCode',
    },
    // V2.9 — PCC power factor + alarm clear
    {
        addr: 40157,
        qty: 1,
        name: 'plant.control.pccPowerFactorGridImport',
        type: 'S16',
        gain: 1000,
        unit: '',
        perm: 'RW',
        desc: 'PCC power factor during grid import (V2.9)',
    },
    {
        addr: 40158,
        qty: 1,
        name: 'plant.control.pccPowerFactorGridExport',
        type: 'S16',
        gain: 1000,
        unit: '',
        perm: 'RW',
        desc: 'PCC power factor during grid export (V2.9)',
    },
    {
        addr: 40159,
        qty: 1,
        name: 'plant.control.gridPowerLossLockoutClear',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'WO',
        desc: 'Grid power loss lockout clear (V2.9)',
    },
];

// ============================================================
// Section 5.3 - Hybrid Inverter Running Info (Read-Only, slave 1-246)
// ============================================================
const INVERTER_READ_REGISTERS = [
    {
        addr: 30500,
        qty: 15,
        name: 'inverter.modelType',
        type: 'STRING',
        gain: null,
        unit: '',
        role: 'info.name',
        desc: 'Model type',
    },
    {
        addr: 30515,
        qty: 10,
        name: 'inverter.serialNumber',
        type: 'STRING',
        gain: null,
        unit: '',
        role: 'info.serial',
        desc: 'Serial number',
    },
    {
        addr: 30525,
        qty: 15,
        name: 'inverter.firmwareVersion',
        type: 'STRING',
        gain: null,
        unit: '',
        role: 'info.firmware',
        desc: 'Machine firmware version',
    },
    {
        addr: 30540,
        qty: 2,
        name: 'inverter.ratedActivePower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Rated active power',
    },
    {
        addr: 30542,
        qty: 2,
        name: 'inverter.maxApparentPower',
        type: 'U32',
        gain: 1000,
        unit: 'kVA',
        role: 'value.power',
        desc: 'Max apparent power',
    },
    {
        addr: 30544,
        qty: 2,
        name: 'inverter.maxActivePower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Max active power',
    },
    {
        addr: 30546,
        qty: 2,
        name: 'inverter.maxAbsorptionPower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Max absorption power',
    },
    {
        addr: 30548,
        qty: 2,
        name: 'inverter.ratedBatteryCapacity',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Rated battery capacity',
    },
    {
        addr: 30550,
        qty: 2,
        name: 'inverter.essRatedChargePower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'ESS rated charge power',
    },
    {
        addr: 30552,
        qty: 2,
        name: 'inverter.essRatedDischargePower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'ESS rated discharge power',
    },
    {
        addr: 30566,
        qty: 2,
        name: 'inverter.essDailyChargeEnergy',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'ESS daily charge energy',
    },
    {
        addr: 30568,
        qty: 4,
        name: 'inverter.essAccumulatedChargeEnergy',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'ESS accumulated charge energy',
    },
    {
        addr: 30572,
        qty: 2,
        name: 'inverter.essDailyDischargeEnergy',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'ESS daily discharge energy',
    },
    {
        addr: 30574,
        qty: 4,
        name: 'inverter.essAccumulatedDischargeEnergy',
        type: 'U64',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'ESS accumulated discharge energy',
    },
    {
        addr: 30578,
        qty: 1,
        name: 'inverter.runningState',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Running state (0=Standby,1=Running,2=Fault,3=Shutdown)',
    },
    {
        addr: 30579,
        qty: 2,
        name: 'inverter.maxActivePowerAdjust',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Max active power adjustment value',
    },
    {
        addr: 30581,
        qty: 2,
        name: 'inverter.minActivePowerAdjust',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Min active power adjustment value',
    },
    {
        addr: 30583,
        qty: 2,
        name: 'inverter.maxReactivePowerFeed',
        type: 'U32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Max reactive power fed to AC',
    },
    {
        addr: 30585,
        qty: 2,
        name: 'inverter.maxReactivePowerAbsorb',
        type: 'U32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Max reactive power absorbed from AC',
    },
    {
        addr: 30587,
        qty: 2,
        name: 'inverter.activePower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Active power',
    },
    {
        addr: 30589,
        qty: 2,
        name: 'inverter.reactivePower',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Reactive power',
    },
    {
        addr: 30591,
        qty: 2,
        name: 'inverter.essMaxBatteryChargePower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'ESS max battery charge power',
    },
    {
        addr: 30593,
        qty: 2,
        name: 'inverter.essMaxBatteryDischargePower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'ESS max battery discharge power',
    },
    {
        addr: 30595,
        qty: 2,
        name: 'inverter.essAvailableBatteryChargeEnergy',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'ESS available battery charge energy',
    },
    {
        addr: 30597,
        qty: 2,
        name: 'inverter.essAvailableBatteryDischargeEnergy',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'ESS available battery discharge energy',
    },
    {
        addr: 30599,
        qty: 2,
        name: 'inverter.essChargeDischargePower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'ESS charge/discharge power',
    },
    {
        addr: 30601,
        qty: 1,
        name: 'inverter.essBatterySoc',
        type: 'U16',
        gain: 10,
        unit: '%',
        role: 'value.battery',
        desc: 'Battery SOC',
    },
    {
        addr: 30602,
        qty: 1,
        name: 'inverter.essBatterySoh',
        type: 'U16',
        gain: 10,
        unit: '%',
        role: 'value.battery',
        desc: 'Battery SOH',
    },
    {
        addr: 30603,
        qty: 1,
        name: 'inverter.essAvgCellTemperature',
        type: 'S16',
        gain: 10,
        unit: '°C',
        role: 'value.temperature',
        desc: 'Average cell temperature',
    },
    {
        addr: 30604,
        qty: 1,
        name: 'inverter.essAvgCellVoltage',
        type: 'U16',
        gain: 1000,
        unit: 'V',
        role: 'value.voltage',
        desc: 'Average cell voltage',
    },
    {
        addr: 30605,
        qty: 1,
        name: 'inverter.alarm1',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Alarm 1 (PCS alarms Appendix 2)',
    },
    {
        addr: 30606,
        qty: 1,
        name: 'inverter.alarm2',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Alarm 2 (PCS alarms Appendix 3)',
    },
    {
        addr: 30607,
        qty: 1,
        name: 'inverter.alarm3',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Alarm 3 (ESS alarms Appendix 4)',
    },
    {
        addr: 30608,
        qty: 1,
        name: 'inverter.alarm4',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Alarm 4 (Gateway alarms Appendix 5)',
    },
    {
        addr: 30609,
        qty: 1,
        name: 'inverter.alarm5',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Alarm 5 (DC Charger alarms Appendix 11)',
    },
    {
        addr: 30620,
        qty: 1,
        name: 'inverter.essMaxBatteryTemperature',
        type: 'S16',
        gain: 10,
        unit: '°C',
        role: 'value.temperature',
        desc: 'Max battery cluster temperature',
    },
    {
        addr: 30621,
        qty: 1,
        name: 'inverter.essMinBatteryTemperature',
        type: 'S16',
        gain: 10,
        unit: '°C',
        role: 'value.temperature',
        desc: 'Min battery cluster temperature',
    },
    {
        addr: 30622,
        qty: 1,
        name: 'inverter.essMaxBatteryCellVoltage',
        type: 'U16',
        gain: 1000,
        unit: 'V',
        role: 'value.voltage',
        desc: 'Max battery cluster cell voltage',
    },
    {
        addr: 30623,
        qty: 1,
        name: 'inverter.essMinBatteryCellVoltage',
        type: 'U16',
        gain: 1000,
        unit: 'V',
        role: 'value.voltage',
        desc: 'Min battery cluster cell voltage',
    },
    {
        addr: 31000,
        qty: 1,
        name: 'inverter.ratedGridVoltage',
        type: 'U16',
        gain: 10,
        unit: 'V',
        role: 'value.voltage',
        desc: 'Rated grid voltage',
    },
    {
        addr: 31001,
        qty: 1,
        name: 'inverter.ratedGridFrequency',
        type: 'U16',
        gain: 100,
        unit: 'Hz',
        role: 'value.frequency',
        desc: 'Rated grid frequency',
    },
    {
        addr: 31002,
        qty: 1,
        name: 'inverter.gridFrequency',
        type: 'U16',
        gain: 100,
        unit: 'Hz',
        role: 'value.frequency',
        desc: 'Grid frequency',
    },
    {
        addr: 31003,
        qty: 1,
        name: 'inverter.pcsInternalTemp',
        type: 'S16',
        gain: 10,
        unit: '°C',
        role: 'value.temperature',
        desc: 'PCS internal temperature',
    },
    {
        addr: 31004,
        qty: 1,
        name: 'inverter.outputType',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Output type: 0=L/N,1=L1/L2/L3,2=L1/L2/L3/N,3=L1/L2/N',
    },
    {
        addr: 31005,
        qty: 2,
        name: 'inverter.abLineVoltage',
        type: 'U32',
        gain: 100,
        unit: 'V',
        role: 'value.voltage',
        desc: 'A-B line voltage',
    },
    {
        addr: 31007,
        qty: 2,
        name: 'inverter.bcLineVoltage',
        type: 'U32',
        gain: 100,
        unit: 'V',
        role: 'value.voltage',
        desc: 'B-C line voltage',
    },
    {
        addr: 31009,
        qty: 2,
        name: 'inverter.caLineVoltage',
        type: 'U32',
        gain: 100,
        unit: 'V',
        role: 'value.voltage',
        desc: 'C-A line voltage',
    },
    {
        addr: 31011,
        qty: 2,
        name: 'inverter.phaseAVoltage',
        type: 'U32',
        gain: 100,
        unit: 'V',
        role: 'value.voltage',
        desc: 'Phase A voltage',
    },
    {
        addr: 31013,
        qty: 2,
        name: 'inverter.phaseBVoltage',
        type: 'U32',
        gain: 100,
        unit: 'V',
        role: 'value.voltage',
        desc: 'Phase B voltage',
    },
    {
        addr: 31015,
        qty: 2,
        name: 'inverter.phaseCVoltage',
        type: 'U32',
        gain: 100,
        unit: 'V',
        role: 'value.voltage',
        desc: 'Phase C voltage',
    },
    {
        addr: 31017,
        qty: 2,
        name: 'inverter.phaseACurrent',
        type: 'S32',
        gain: 100,
        unit: 'A',
        role: 'value.current',
        desc: 'Phase A current',
    },
    {
        addr: 31019,
        qty: 2,
        name: 'inverter.phaseBCurrent',
        type: 'S32',
        gain: 100,
        unit: 'A',
        role: 'value.current',
        desc: 'Phase B current',
    },
    {
        addr: 31021,
        qty: 2,
        name: 'inverter.phaseCCurrent',
        type: 'S32',
        gain: 100,
        unit: 'A',
        role: 'value.current',
        desc: 'Phase C current',
    },
    {
        addr: 31023,
        qty: 1,
        name: 'inverter.powerFactor',
        type: 'U16',
        gain: 1000,
        unit: '',
        role: 'value',
        desc: 'Power factor',
    },
    {
        addr: 31024,
        qty: 1,
        name: 'inverter.packCount',
        type: 'U16',
        gain: 1,
        unit: '',
        role: 'value',
        desc: 'PACK count',
    },
    {
        addr: 31025,
        qty: 1,
        name: 'inverter.pvStringCount',
        type: 'U16',
        gain: 1,
        unit: '',
        role: 'value',
        desc: 'PV string count',
    },
    {
        addr: 31026,
        qty: 1,
        name: 'inverter.mpptCount',
        type: 'U16',
        gain: 1,
        unit: '',
        role: 'value',
        desc: 'MPPT count',
    },
    {
        addr: 31027,
        qty: 1,
        name: 'inverter.pv1Voltage',
        type: 'S16',
        gain: 10,
        unit: 'V',
        role: 'value.voltage',
        desc: 'PV1 voltage',
    },
    {
        addr: 31028,
        qty: 1,
        name: 'inverter.pv1Current',
        type: 'S16',
        gain: 100,
        unit: 'A',
        role: 'value.current',
        desc: 'PV1 current',
    },
    {
        addr: 31029,
        qty: 1,
        name: 'inverter.pv2Voltage',
        type: 'S16',
        gain: 10,
        unit: 'V',
        role: 'value.voltage',
        desc: 'PV2 voltage',
    },
    {
        addr: 31030,
        qty: 1,
        name: 'inverter.pv2Current',
        type: 'S16',
        gain: 100,
        unit: 'A',
        role: 'value.current',
        desc: 'PV2 current',
    },
    {
        addr: 31031,
        qty: 1,
        name: 'inverter.pv3Voltage',
        type: 'S16',
        gain: 10,
        unit: 'V',
        role: 'value.voltage',
        desc: 'PV3 voltage',
    },
    {
        addr: 31032,
        qty: 1,
        name: 'inverter.pv3Current',
        type: 'S16',
        gain: 100,
        unit: 'A',
        role: 'value.current',
        desc: 'PV3 current',
    },
    {
        addr: 31033,
        qty: 1,
        name: 'inverter.pv4Voltage',
        type: 'S16',
        gain: 10,
        unit: 'V',
        role: 'value.voltage',
        desc: 'PV4 voltage',
    },
    {
        addr: 31034,
        qty: 1,
        name: 'inverter.pv4Current',
        type: 'S16',
        gain: 100,
        unit: 'A',
        role: 'value.current',
        desc: 'PV4 current',
    },
    {
        addr: 31035,
        qty: 2,
        name: 'inverter.pvPower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'PV power',
    },
    {
        addr: 31037,
        qty: 1,
        name: 'inverter.insulationResistance',
        type: 'U16',
        gain: 1000,
        unit: 'MΩ',
        role: 'value',
        desc: 'Insulation resistance',
    },
    {
        addr: 31038,
        qty: 2,
        name: 'inverter.startupTime',
        type: 'U32',
        gain: 1,
        unit: 's',
        role: 'value.time',
        desc: 'Startup time (epoch)',
    },
    {
        addr: 31040,
        qty: 2,
        name: 'inverter.shutdownTime',
        type: 'U32',
        gain: 1,
        unit: 's',
        role: 'value.time',
        desc: 'Shutdown time (epoch)',
    },
    // V2.6 — adjustment feedback (separate FC04 group)
    {
        addr: 30613,
        qty: 2,
        name: 'inverter.activePowerFixedAdjFeedback',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Active power fixed adjustment feedback (V2.6)',
    },
    {
        addr: 30615,
        qty: 2,
        name: 'inverter.reactivePowerFixedAdjFeedback',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        role: 'value.power',
        desc: 'Reactive power fixed adjustment feedback (V2.6)',
    },
    {
        addr: 30617,
        qty: 1,
        name: 'inverter.activePowerPctAdjFeedback',
        type: 'S16',
        gain: 100,
        unit: '%',
        role: 'value',
        desc: 'Active power percentage adjustment feedback (V2.6)',
    },
    {
        addr: 30618,
        qty: 1,
        name: 'inverter.reactivePowerQsAdjFeedback',
        type: 'S16',
        gain: 100,
        unit: '%',
        role: 'value',
        desc: 'Reactive power Q/S adjustment feedback (V2.6)',
    },
    {
        addr: 30619,
        qty: 1,
        name: 'inverter.powerFactorAdjFeedback',
        type: 'S16',
        gain: 1000,
        unit: '',
        role: 'value',
        desc: 'Power factor adjustment feedback (V2.6)',
    },
    // V2.6 — separate FC04 group (gap > 4 from 31041)
    {
        addr: 31509,
        qty: 2,
        name: 'inverter.pvDailyGeneration',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'PV daily generation (V2.6)',
    },
    {
        addr: 31511,
        qty: 2,
        name: 'inverter.pvTotalGeneration',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'PV total generation (V2.6)',
    },
];

// ============================================================
// Section 5.4 - Hybrid Inverter Parameter Setting (Holding, slave 1-246)
// ============================================================
const INVERTER_WRITE_REGISTERS = [
    {
        addr: 40500,
        qty: 1,
        name: 'inverter.control.startStop',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'WO',
        desc: 'Start/Stop: 0=Stop, 1=Start',
    },
    // addr 40501 (gridCode) removed in V2.7
    // addr 41500 (remoteEmsDispatchEnable) removed in V2.8
    {
        addr: 41501,
        qty: 2,
        name: 'inverter.control.activePowerFixed',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        perm: 'RW',
        desc: 'Active power fixed value adjustment',
    },
    {
        addr: 41503,
        qty: 2,
        name: 'inverter.control.reactivePowerFixed',
        type: 'S32',
        gain: 1000,
        unit: 'kVar',
        perm: 'RW',
        desc: 'Reactive power fixed value adjustment',
    },
    {
        addr: 41505,
        qty: 1,
        name: 'inverter.control.activePowerPercent',
        type: 'S16',
        gain: 100,
        unit: '%',
        perm: 'RW',
        desc: 'Active power percentage adjustment',
    },
    {
        addr: 41506,
        qty: 1,
        name: 'inverter.control.reactivePowerQS',
        type: 'S16',
        gain: 100,
        unit: '%',
        perm: 'RW',
        desc: 'Reactive power Q/S adjustment',
    },
    {
        addr: 41507,
        qty: 1,
        name: 'inverter.control.powerFactor',
        type: 'S16',
        gain: 1000,
        unit: '',
        perm: 'RW',
        desc: 'Power factor adjustment',
    },
];

// DC Charger write registers
const DC_CHARGER_WRITE_REGISTERS = [
    {
        addr: 41000,
        qty: 1,
        name: 'dcCharger.control.startStop',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'WO',
        desc: 'Start/Stop: 0=Start, 1=Stop',
    },
    // V2.9 — power limits
    {
        addr: 41002,
        qty: 2,
        name: 'dcCharger.control.maxChargingPowerLimit',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        perm: 'RW',
        desc: 'Max charging power limit (V2.9)',
    },
    {
        addr: 41004,
        qty: 2,
        name: 'dcCharger.control.maxDischargingPowerLimit',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        perm: 'RW',
        desc: 'Max discharging power limit (V2.9)',
    },
];

// ============================================================
// Section 5.5 - AC-Charger Running Info (Read-Only, slave 1-246)
// ============================================================
const AC_CHARGER_READ_REGISTERS = [
    {
        addr: 32000,
        qty: 1,
        name: 'acCharger.systemState',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'System state (IEC61851-1)',
    },
    {
        addr: 32001,
        qty: 2,
        name: 'acCharger.totalEnergyConsumed',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total energy consumed',
    },
    {
        addr: 32003,
        qty: 2,
        name: 'acCharger.chargingPower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Charging power',
    },
    {
        addr: 32005,
        qty: 2,
        name: 'acCharger.ratedPower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Rated power',
    },
    {
        addr: 32007,
        qty: 2,
        name: 'acCharger.ratedCurrent',
        type: 'S32',
        gain: 100,
        unit: 'A',
        role: 'value.current',
        desc: 'Rated current',
    },
    {
        addr: 32009,
        qty: 1,
        name: 'acCharger.ratedVoltage',
        type: 'U16',
        gain: 10,
        unit: 'V',
        role: 'value.voltage',
        desc: 'Rated voltage',
    },
    {
        addr: 32010,
        qty: 2,
        name: 'acCharger.inputBreakerRatedCurrent',
        type: 'S32',
        gain: 100,
        unit: 'A',
        role: 'value.current',
        desc: 'AC-Charger input breaker rated current',
    },
    {
        addr: 32012,
        qty: 1,
        name: 'acCharger.alarm1',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Alarm 1 (Appendix 8)',
    },
    {
        addr: 32013,
        qty: 1,
        name: 'acCharger.alarm2',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Alarm 2 (Appendix 9)',
    },
    {
        addr: 32014,
        qty: 1,
        name: 'acCharger.alarm3',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Alarm 3 (Appendix 10)',
    },
];

// ============================================================
// Section 5.6 - AC-Charger Parameter Setting (Holding, slave 1-246)
// ============================================================
const AC_CHARGER_WRITE_REGISTERS = [
    {
        addr: 42000,
        qty: 1,
        name: 'acCharger.control.startStop',
        type: 'U16',
        gain: null,
        unit: '',
        perm: 'WO',
        desc: 'Start/Stop: 0=Start, 1=Stop',
    },
    {
        addr: 42001,
        qty: 2,
        name: 'acCharger.control.outputCurrent',
        type: 'U32',
        gain: 100,
        unit: 'A',
        perm: 'RW',
        desc: 'Charger output current [6, rated]',
    },
];

// DC Charger reading registers (part of inverter slave)
const DC_CHARGER_READ_REGISTERS = [
    {
        addr: 31500,
        qty: 1,
        name: 'dcCharger.vehicleBatteryVoltage',
        type: 'U16',
        gain: 10,
        unit: 'V',
        role: 'value.voltage',
        desc: 'Vehicle battery voltage',
    },
    {
        addr: 31501,
        qty: 1,
        name: 'dcCharger.chargingCurrent',
        type: 'U16',
        gain: 10,
        unit: 'A',
        role: 'value.current',
        desc: 'Charging current',
    },
    {
        addr: 31502,
        qty: 2,
        name: 'dcCharger.outputPower',
        type: 'S32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Output power',
    },
    {
        addr: 31504,
        qty: 1,
        name: 'dcCharger.vehicleSoc',
        type: 'U16',
        gain: 10,
        unit: '%',
        role: 'value.battery',
        desc: 'Vehicle SOC',
    },
    {
        addr: 31505,
        qty: 2,
        name: 'dcCharger.currentChargingCapacity',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Current charging capacity (single session)',
    },
    {
        addr: 31507,
        qty: 2,
        name: 'dcCharger.currentChargingDuration',
        type: 'U32',
        gain: 1,
        unit: 's',
        role: 'value.time',
        desc: 'Current charging duration (single session)',
    },
    // V2.8/V2.9 — separate FC04 group (gap of 5 from 31508)
    {
        addr: 31513,
        qty: 1,
        name: 'dcCharger.runningState',
        type: 'U16',
        gain: null,
        unit: '',
        role: 'value',
        desc: 'Running state (V2.8)',
    },
    {
        addr: 31514,
        qty: 1,
        name: 'dcCharger.dischargingCurrent',
        type: 'U16',
        gain: 10,
        unit: 'A',
        role: 'value.current',
        desc: 'Discharging current (V2.9)',
    },
    {
        addr: 31515,
        qty: 2,
        name: 'dcCharger.currentDischargingCapacity',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Current discharging capacity (single session, V2.9)',
    },
    {
        addr: 31517,
        qty: 2,
        name: 'dcCharger.currentDischargingDuration',
        type: 'U32',
        gain: 1,
        unit: 's',
        role: 'value.time',
        desc: 'Current discharging duration (single session, V2.9)',
    },
    {
        addr: 31519,
        qty: 2,
        name: 'dcCharger.totalChargingCapacity',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total charging capacity (V2.9)',
    },
    {
        addr: 31521,
        qty: 2,
        name: 'dcCharger.totalDischargingCapacity',
        type: 'U32',
        gain: 100,
        unit: 'kWh',
        role: 'value.energy',
        desc: 'Total discharging capacity (V2.9)',
    },
    {
        addr: 31523,
        qty: 2,
        name: 'dcCharger.ratedChargingPower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Rated charging power (V2.9)',
    },
    {
        addr: 31525,
        qty: 2,
        name: 'dcCharger.ratedDischargingPower',
        type: 'U32',
        gain: 1000,
        unit: 'kW',
        role: 'value.power',
        desc: 'Rated discharging power (V2.9)',
    },
];

// Running state values
const RUNNING_STATES = {
    0x00: 'Standby',
    0x01: 'Running',
    0x02: 'Fault',
    0x03: 'Shutdown',
    0x07: 'Environmental Abnormality',
};

// EMS work modes
const EMS_WORK_MODES = {
    0: 'Max Self Consumption',
    1: 'AI Mode',
    2: 'TOU',
    5: 'Full Feed-in to Grid',
    7: 'Remote EMS',
    9: 'Custom',
};

// Remote EMS control modes
const REMOTE_EMS_MODES = {
    0x00: 'PCS Remote Control',
    0x01: 'Standby',
    0x02: 'Maximum Self-Consumption',
    0x03: 'Command Charging (Grid First)',
    0x04: 'Command Charging (PV First)',
    0x05: 'Command Discharging (PV First)',
    0x06: 'Command Discharging (ESS First)',
    0x07: 'Reserved',
    0x08: 'V2G',
};

// ============================================================
// Section 5.7 - PSS (Power Station Switch) Running Info (Input, slave configurable)
// ============================================================
const PSS_READ_REGISTERS = [
    { addr: 32500, qty: 15, name: 'pss.model',              type: 'STRING', gain: null, unit: '',    role: 'text',              desc: 'PSS model' },
    { addr: 32515, qty: 10, name: 'pss.serialNumber',       type: 'STRING', gain: null, unit: '',    role: 'text',              desc: 'PSS serial number' },
    { addr: 32525, qty: 15, name: 'pss.firmwareVersion',    type: 'STRING', gain: null, unit: '',    role: 'text',              desc: 'PSS firmware version' },
    { addr: 32540, qty: 1,  name: 'pss.communicationStatus',type: 'U16',   gain: null, unit: '',    role: 'value',             desc: 'Communication status (V2.9)' },
    { addr: 32541, qty: 1,  name: 'pss.teleindication1',    type: 'U16',   gain: null, unit: '',    role: 'value',             desc: 'Teleindication 1 (Appendix 15)' },
    { addr: 32542, qty: 1,  name: 'pss.teleindication2',    type: 'U16',   gain: null, unit: '',    role: 'value',             desc: 'Teleindication 2 (Appendix 16)' },
    { addr: 32543, qty: 1,  name: 'pss.teleindication3',    type: 'U16',   gain: null, unit: '',    role: 'value',             desc: 'Teleindication 3 (Appendix 17)' },
    { addr: 32544, qty: 1,  name: 'pss.teleindication4',    type: 'U16',   gain: null, unit: '',    role: 'value',             desc: 'Teleindication 4 (Appendix 18)' },
    { addr: 32545, qty: 1,  name: 'pss.teleindication5',    type: 'U16',   gain: null, unit: '',    role: 'value',             desc: 'Teleindication 5 (Appendix 19)' },
    { addr: 32546, qty: 2,  name: 'pss.mvCurrentPhaseA',    type: 'S32',   gain: 1000, unit: 'A',   role: 'value.current',     desc: 'MV current Phase A' },
    { addr: 32548, qty: 2,  name: 'pss.mvCurrentPhaseB',    type: 'S32',   gain: 1000, unit: 'A',   role: 'value.current',     desc: 'MV current Phase B' },
    { addr: 32550, qty: 2,  name: 'pss.mvCurrentPhaseC',    type: 'S32',   gain: 1000, unit: 'A',   role: 'value.current',     desc: 'MV current Phase C' },
    { addr: 32552, qty: 2,  name: 'pss.mvZeroSeqCurrent',   type: 'S32',   gain: 1000, unit: 'A',   role: 'value.current',     desc: 'MV zero-sequence current' },
    { addr: 32554, qty: 1,  name: 'pss.mvFrequency',        type: 'U16',   gain: 100,  unit: 'Hz',  role: 'value.frequency',   desc: 'MV frequency' },
    { addr: 32555, qty: 1,  name: 'pss.mvTemperature',      type: 'S16',   gain: 10,   unit: '°C',  role: 'value.temperature', desc: 'MV temperature' },
    { addr: 32556, qty: 1,  name: 'pss.mvHumidity',         type: 'U16',   gain: 10,   unit: '%',   role: 'value.humidity',    desc: 'MV humidity' },
    { addr: 32557, qty: 1,  name: 'pss.cableTempG1A',       type: 'S16',   gain: 10,   unit: '°C',  role: 'value.temperature', desc: 'Cable temperature G1 Phase A' },
    { addr: 32558, qty: 1,  name: 'pss.cableTempG1B',       type: 'S16',   gain: 10,   unit: '°C',  role: 'value.temperature', desc: 'Cable temperature G1 Phase B' },
    { addr: 32559, qty: 1,  name: 'pss.cableTempG1C',       type: 'S16',   gain: 10,   unit: '°C',  role: 'value.temperature', desc: 'Cable temperature G1 Phase C' },
    { addr: 32560, qty: 1,  name: 'pss.cableTempG2A',       type: 'S16',   gain: 10,   unit: '°C',  role: 'value.temperature', desc: 'Cable temperature G2 Phase A' },
    { addr: 32561, qty: 1,  name: 'pss.cableTempG2B',       type: 'S16',   gain: 10,   unit: '°C',  role: 'value.temperature', desc: 'Cable temperature G2 Phase B' },
    { addr: 32562, qty: 1,  name: 'pss.cableTempG2C',       type: 'S16',   gain: 10,   unit: '°C',  role: 'value.temperature', desc: 'Cable temperature G2 Phase C' },
    { addr: 32563, qty: 1,  name: 'pss.cableTempG3A',       type: 'S16',   gain: 10,   unit: '°C',  role: 'value.temperature', desc: 'Cable temperature G3 Phase A' },
    { addr: 32564, qty: 1,  name: 'pss.cableTempG3B',       type: 'S16',   gain: 10,   unit: '°C',  role: 'value.temperature', desc: 'Cable temperature G3 Phase B' },
    { addr: 32565, qty: 1,  name: 'pss.cableTempG3C',       type: 'S16',   gain: 10,   unit: '°C',  role: 'value.temperature', desc: 'Cable temperature G3 Phase C' },
    // LA LV Switchgear (gap 32566–32569 = 4 registers, within FC04 batch tolerance)
    { addr: 32570, qty: 2,  name: 'pss.laVoltagePhaseA',    type: 'U32',   gain: 100,  unit: 'V',   role: 'value.voltage',     desc: 'LA LV switchgear voltage Phase A' },
    { addr: 32572, qty: 2,  name: 'pss.laVoltagePhaseB',    type: 'U32',   gain: 100,  unit: 'V',   role: 'value.voltage',     desc: 'LA LV switchgear voltage Phase B' },
    { addr: 32574, qty: 2,  name: 'pss.laVoltagePhaseC',    type: 'U32',   gain: 100,  unit: 'V',   role: 'value.voltage',     desc: 'LA LV switchgear voltage Phase C' },
    { addr: 32576, qty: 2,  name: 'pss.laCurrentPhaseA',    type: 'S32',   gain: 1000, unit: 'A',   role: 'value.current',     desc: 'LA LV switchgear current Phase A' },
    { addr: 32578, qty: 2,  name: 'pss.laCurrentPhaseB',    type: 'S32',   gain: 1000, unit: 'A',   role: 'value.current',     desc: 'LA LV switchgear current Phase B' },
    { addr: 32580, qty: 2,  name: 'pss.laCurrentPhaseC',    type: 'S32',   gain: 1000, unit: 'A',   role: 'value.current',     desc: 'LA LV switchgear current Phase C' },
    { addr: 32582, qty: 2,  name: 'pss.laActivePower',      type: 'S32',   gain: 1000, unit: 'kW',  role: 'value.power',       desc: 'LA LV active power' },
    { addr: 32584, qty: 2,  name: 'pss.laReactivePower',    type: 'S32',   gain: 1000, unit: 'kVar',role: 'value.power',       desc: 'LA LV reactive power' },
    { addr: 32586, qty: 4,  name: 'pss.laTotalEnergy',      type: 'U64',   gain: 100,  unit: 'kWh', role: 'value.energy',      desc: 'LA LV total energy' },
    // LB LV Switchgear
    { addr: 32590, qty: 2,  name: 'pss.lbVoltagePhaseA',    type: 'U32',   gain: 100,  unit: 'V',   role: 'value.voltage',     desc: 'LB LV switchgear voltage Phase A' },
    { addr: 32592, qty: 2,  name: 'pss.lbVoltagePhaseB',    type: 'U32',   gain: 100,  unit: 'V',   role: 'value.voltage',     desc: 'LB LV switchgear voltage Phase B' },
    { addr: 32594, qty: 2,  name: 'pss.lbVoltagePhaseC',    type: 'U32',   gain: 100,  unit: 'V',   role: 'value.voltage',     desc: 'LB LV switchgear voltage Phase C' },
    { addr: 32596, qty: 2,  name: 'pss.lbCurrentPhaseA',    type: 'S32',   gain: 1000, unit: 'A',   role: 'value.current',     desc: 'LB LV switchgear current Phase A' },
    { addr: 32598, qty: 2,  name: 'pss.lbCurrentPhaseB',    type: 'S32',   gain: 1000, unit: 'A',   role: 'value.current',     desc: 'LB LV switchgear current Phase B' },
    { addr: 32600, qty: 2,  name: 'pss.lbCurrentPhaseC',    type: 'S32',   gain: 1000, unit: 'A',   role: 'value.current',     desc: 'LB LV switchgear current Phase C' },
    { addr: 32602, qty: 2,  name: 'pss.lbActivePower',      type: 'S32',   gain: 1000, unit: 'kW',  role: 'value.power',       desc: 'LB LV active power' },
    { addr: 32604, qty: 2,  name: 'pss.lbReactivePower',    type: 'S32',   gain: 1000, unit: 'kVar',role: 'value.power',       desc: 'LB LV reactive power' },
    { addr: 32606, qty: 4,  name: 'pss.lbTotalEnergy',      type: 'U64',   gain: 100,  unit: 'kWh', role: 'value.energy',      desc: 'LB LV total energy' },
    // Transformer temperatures
    { addr: 32610, qty: 1,  name: 'pss.transformerOilTemp',       type: 'S16', gain: 10, unit: '°C', role: 'value.temperature', desc: 'Transformer oil temperature' },
    { addr: 32611, qty: 1,  name: 'pss.transformerWindingTempA',  type: 'S16', gain: 10, unit: '°C', role: 'value.temperature', desc: 'Transformer winding temperature Phase A' },
    { addr: 32612, qty: 1,  name: 'pss.transformerWindingTempB',  type: 'S16', gain: 10, unit: '°C', role: 'value.temperature', desc: 'Transformer winding temperature Phase B' },
    { addr: 32613, qty: 1,  name: 'pss.transformerWindingTempC',  type: 'S16', gain: 10, unit: '°C', role: 'value.temperature', desc: 'Transformer winding temperature Phase C' },
    // Distribution cabinet (gap 32614–32619 = 6 registers → separate FC04 group)
    { addr: 32620, qty: 2,  name: 'pss.distVoltage',        type: 'U32',   gain: 100,  unit: 'V',   role: 'value.voltage',     desc: 'Distribution cabinet voltage' },
    { addr: 32622, qty: 2,  name: 'pss.distCurrent',        type: 'S32',   gain: 1000, unit: 'A',   role: 'value.current',     desc: 'Distribution cabinet current' },
    { addr: 32624, qty: 2,  name: 'pss.distActivePower',    type: 'S32',   gain: 1000, unit: 'kW',  role: 'value.power',       desc: 'Distribution cabinet active power' },
    { addr: 32626, qty: 2,  name: 'pss.distReactivePower',  type: 'S32',   gain: 1000, unit: 'kVar',role: 'value.power',       desc: 'Distribution cabinet reactive power' },
    { addr: 32628, qty: 4,  name: 'pss.distTotalEnergy',    type: 'U64',   gain: 100,  unit: 'kWh', role: 'value.energy',      desc: 'Distribution cabinet total energy' },
];

// ============================================================
// Section 5.8 - PSS Parameter Setting (Holding, slave configurable)
// ============================================================
const PSS_WRITE_REGISTERS = [
    { addr: 42500, qty: 1, name: 'pss.control.g3Breaker',  type: 'U16', gain: null, unit: '', perm: 'RW', desc: 'G3 circuit breaker: 0=Open, 1=Close' },
    { addr: 42501, qty: 1, name: 'pss.control.laSwitch',   type: 'U16', gain: null, unit: '', perm: 'RW', desc: 'LA LV switch: 0=Open, 1=Close' },
    { addr: 42502, qty: 1, name: 'pss.control.lbSwitch',   type: 'U16', gain: null, unit: '', perm: 'RW', desc: 'LB LV switch: 0=Open, 1=Close' },
];

// ============================================================
// Section 5.9 - PID (PV Insulation Detection) Running Info (Input, slave configurable)
// ============================================================
const PID_READ_REGISTERS = [
    { addr: 33000, qty: 15, name: 'pid.model',              type: 'STRING', gain: null, unit: '',   role: 'text',              desc: 'PID model' },
    { addr: 33015, qty: 10, name: 'pid.serialNumber',       type: 'STRING', gain: null, unit: '',   role: 'text',              desc: 'PID serial number' },
    { addr: 33025, qty: 15, name: 'pid.firmwareVersion',    type: 'STRING', gain: null, unit: '',   role: 'text',              desc: 'PID firmware version' },
    { addr: 33040, qty: 1,  name: 'pid.communicationStatus',type: 'U16',   gain: null, unit: '',   role: 'value',             desc: 'Communication status (V2.9)' },
    { addr: 33041, qty: 1,  name: 'pid.runningState',       type: 'U16',   gain: null, unit: '',   role: 'value',             desc: 'PID operating status' },
    { addr: 33042, qty: 2,  name: 'pid.voltageAB',          type: 'U32',   gain: 100,  unit: 'V',  role: 'value.voltage',     desc: 'Line voltage AB' },
    { addr: 33044, qty: 2,  name: 'pid.voltageBC',          type: 'U32',   gain: 100,  unit: 'V',  role: 'value.voltage',     desc: 'Line voltage BC' },
    { addr: 33046, qty: 2,  name: 'pid.voltageCA',          type: 'U32',   gain: 100,  unit: 'V',  role: 'value.voltage',     desc: 'Line voltage CA' },
    { addr: 33048, qty: 2,  name: 'pid.voltagePhaseA',      type: 'U32',   gain: 100,  unit: 'V',  role: 'value.voltage',     desc: 'Phase voltage A' },
    { addr: 33050, qty: 2,  name: 'pid.voltagePhaseB',      type: 'U32',   gain: 100,  unit: 'V',  role: 'value.voltage',     desc: 'Phase voltage B' },
    { addr: 33052, qty: 2,  name: 'pid.voltagePhaseC',      type: 'U32',   gain: 100,  unit: 'V',  role: 'value.voltage',     desc: 'Phase voltage C' },
    { addr: 33054, qty: 1,  name: 'pid.frequency',          type: 'U16',   gain: 100,  unit: 'Hz', role: 'value.frequency',   desc: 'Grid frequency' },
    { addr: 33055, qty: 2,  name: 'pid.outputVoltage',      type: 'U32',   gain: 100,  unit: 'V',  role: 'value.voltage',     desc: 'Output voltage' },
    { addr: 33057, qty: 2,  name: 'pid.busVoltage',         type: 'U32',   gain: 100,  unit: 'V',  role: 'value.voltage',     desc: 'Bus voltage' },
    { addr: 33059, qty: 2,  name: 'pid.outputCurrent',      type: 'S32',   gain: 1000, unit: 'A',  role: 'value.current',     desc: 'Output current' },
    { addr: 33061, qty: 1,  name: 'pid.temperature1',       type: 'S16',   gain: 10,   unit: '°C', role: 'value.temperature', desc: 'Internal temperature 1' },
    { addr: 33062, qty: 1,  name: 'pid.temperature2',       type: 'S16',   gain: 10,   unit: '°C', role: 'value.temperature', desc: 'Internal temperature 2' },
    { addr: 33063, qty: 1,  name: 'pid.temperature3',       type: 'S16',   gain: 10,   unit: '°C', role: 'value.temperature', desc: 'Internal temperature 3' },
    { addr: 33064, qty: 1,  name: 'pid.temperature4',       type: 'S16',   gain: 10,   unit: '°C', role: 'value.temperature', desc: 'Internal temperature 4' },
    { addr: 33065, qty: 1,  name: 'pid.temperature5',       type: 'S16',   gain: 10,   unit: '°C', role: 'value.temperature', desc: 'Internal temperature 5' },
    { addr: 33066, qty: 1,  name: 'pid.alarm1',             type: 'U16',   gain: null, unit: '',   role: 'value',             desc: 'Alarm 1 (Appendix 20)' },
    { addr: 33067, qty: 1,  name: 'pid.alarm2',             type: 'U16',   gain: null, unit: '',   role: 'value',             desc: 'Alarm 2 (Appendix 21)' },
];

// ============================================================
// Section 5.10 - PID Parameter Setting (Holding, slave configurable)
// ============================================================
const PID_WRITE_REGISTERS = [
    { addr: 43000, qty: 1, name: 'pid.control.startStop', type: 'U16', gain: null, unit: '', perm: 'WO', desc: 'Start/Stop: 0=Stop, 1=Start' },
];

// ============================================================
// Section 5.11 - ESS Preheating Parameter Setting (Holding, slave 247, M1-HYA/HYB only)
// ============================================================
const ESS_PREHEATING_WRITE_REGISTERS = (() => {
    const regs = [
        { addr: 50000, qty: 1, name: 'plant.essPreheating.enable',        type: 'U16', gain: null, unit: '', perm: 'RW', desc: 'Preheating enable: 0=Disable, 1=Enable' },
        { addr: 50001, qty: 1, name: 'plant.essPreheating.mode',          type: 'U16', gain: null, unit: '', perm: 'RW', desc: 'Preheating mode: 0=Auto, 1=Manual' },
        { addr: 50002, qty: 1, name: 'plant.essPreheating.advanceEnable', type: 'U16', gain: null, unit: '', perm: 'RW', desc: 'Advance preheating enable: 0=Disable, 1=Enable' },
    ];
    for (let n = 1; n <= 30; n++) {
        const base = 50003 + (n - 1) * 6;
        regs.push({ addr: base,     qty: 2, name: `plant.essPreheating.tou${n}.startTime`, type: 'U32', gain: null, unit: 's',  perm: 'RW', desc: `TOU ${n} start time` });
        regs.push({ addr: base + 2, qty: 2, name: `plant.essPreheating.tou${n}.endTime`,   type: 'U32', gain: null, unit: 's',  perm: 'RW', desc: `TOU ${n} end time` });
        regs.push({ addr: base + 4, qty: 2, name: `plant.essPreheating.tou${n}.power`,     type: 'S32', gain: 1000, unit: 'kW', perm: 'RW', desc: `TOU ${n} preheating power` });
    }
    regs.push({ addr: 50183, qty: 1, name: 'plant.essPreheating.reservedSoc', type: 'U16', gain: 100, unit: '%', perm: 'RW', desc: 'Preheating reserved SOC' });
    return regs;
})();

// DC Charger running state values (V2.8/V2.9)
const DC_CHARGER_RUNNING_STATES = {
    0x00: 'Idle',
    0x01: 'Occupied',
    0x02: 'Preparing (Communication)',
    0x03: 'Charging',
    0x04: 'Fault',
    0x05: 'Scheduled',
    0x06: 'Ended',
    0x07: 'Unavailable',
    0x08: 'Discharging',
    0x09: 'Alarm',
    0x0A: 'Preparing (Insulation)',
};

module.exports = {
    PLANT_READ_REGISTERS,
    PLANT_WRITE_REGISTERS,
    INVERTER_READ_REGISTERS,
    INVERTER_WRITE_REGISTERS,
    DC_CHARGER_READ_REGISTERS,
    DC_CHARGER_WRITE_REGISTERS,
    AC_CHARGER_READ_REGISTERS,
    AC_CHARGER_WRITE_REGISTERS,
    PSS_READ_REGISTERS,
    PSS_WRITE_REGISTERS,
    PID_READ_REGISTERS,
    PID_WRITE_REGISTERS,
    ESS_PREHEATING_WRITE_REGISTERS,
    RUNNING_STATES,
    EMS_WORK_MODES,
    REMOTE_EMS_MODES,
    DC_CHARGER_RUNNING_STATES,
};
